image: node:latest

include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - lint
  - analysis
  - test
  - registry
  - deploy

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - ~/.cache/

.lint:
  stage: lint
  script:
    - npm install eslint -g
    - npm install -g --only=dev
    - npm install eslint-plugin-react@latest
    - eslint --fix --max-warnings 20 src/ || echo "Skipping errors for now..."

code_quality:
  stage: test

code_quality:
  stage: analysis
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
    SP_VERSION: 0.85.6
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/ci-cd/codequality:$SP_VERSION" /src
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

test:
  stage: test
  script:
    - echo "Testing..."

docker:
  stage: registry
  image: docker:stable
  only:
    - master
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  script:
    - echo "Building and uploading Docker image 🐳"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH

deploy:
  stage: deploy
  trigger: tqs-domus/compose
  only:
    - master
